name: Bug report
description: Report a reproducible bug in code, docs, or benchmarks
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide a minimal reproduction.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, GPU/CPU details
      placeholder: "Windows 11, Python 3.11, CUDA 12.8, RTX 4090"
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command run
      placeholder: "python resnet50_benchmark.py ..."
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error logs or traceback
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
